# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



User.destroy_all
Post.destroy_all
Image.destroy_all
Destination.destroy_all

tyler = User.create!(username: 'T-Pain', image: 'https://files.slack.com/files-pri/T0351JZQ0-FA60SC97X/screen_shot_2018-02-20_at_12.54.22_pm.png', email: 'dopest@snailmail.com' , location: 'The top, bitch!')
cricket = User.create!(username: 'Cricket', image: 'https://files.slack.com/files-tmb/T0351JZQ0-FA6MC4T7Y-9e13997841/image_uploaded_from_ios_1024.jpg', email: 'cricketmcgillicuddy@aol.com', location: 'Will\'s mom\'s house' )
sj = User.create!(username: 'Sweety', image: 'https://slack-imgs.com/?c=1&url=https%3A%2F%2Fscontent-iad3-1.xx.fbcdn.net%2Fv%2Ft1.0-9%2F30571400_10155535695339150_9020289133943193600_n.jpg%3F_nc_cat%3D0%26oh%3D6a39ddd3d0b98bb0e961a6d88f792c7f%26oe%3D5B719ED2' , email: 'sjk@gmail.com', location: 'ATL!!!')
owen = User.create!(username: 'Owen', image: 'https://www.drummercafe.com/media/com_mtree/images/listings/m/271.jpg', email: 'owen@drumgod.com' , location: 'Mercedes Benz Stadium')
bennett = User.create!(username: 'B-rock', image: 'https://files.slack.com/files-pri/T0351JZQ0-FA5P6D8R0/10523147_894409773904492_7039320791338872224_n.jpg', email: 'myemail@myemail.com', location: 'Inman Park')
josh = User.create!(username: 'S4f3ty' , image: 'https://media.licdn.com/dms/image/C4E03AQF0yZmy5aAz9g/profile-displayphoto-shrink_200_200/0?e=1528592400&v=beta&t=fHbYRhKC7Jz-rlOY110O6a_D7PleEkZpkmp3J02hu84', email: 'fielddayforthesundays@gmail.com' , location: 'Murph\'s mom\'s bedroom' )
murphdawg = User.create!(username: 'MurphDawg' , image: 'https://media.licdn.com/dms/image/C4E03AQHm8ZI5qfxY5g/profile-displayphoto-shrink_800_800/0?e=1528592400&v=beta&t=_XhlapRYG0v5AdBnivugDPNDc3gDOVr6uAhKXNyq2OM', email: 'jdawg@email.com' , location: 'Lawrenceville, GA' )
camcam = User.create!(username: 'CamCam', image: 'https://files.slack.com/files-pri/T0351JZQ0-FA4ND5FFX/cam5.jpg', email: 'dookie@emailstuff.com', location: 'EAV')
wilhelm = User.create!(username: 'KaiserWilhelm', image: 'https://slack-imgs.com/?c=1&url=https%3A%2F%2Fscontent-iad3-1.cdninstagram.com%2Fvp%2Fa809ee8afe368b58be91410560133798%2F5B68F917%2Ft51.2885-15%2Fe35%2F29715234_184604269015290_6993511221060173824_n.jpg', email: 'zeitgeist@germanic.com', location: 'Don\'t Care' )
blake = User.create!(username: 'NatureboyBlakeSavage', image: 'https://ca.slack-edge.com/T0351JZQ0-U6V8GUE4X-a20f62c507d7-1024', email:'kittykat@hellokitty.com' , location: 'Atlanta, GA' )

 destination1 = Destination.create!(title: 'Toccoa Falls', image: 'https://photos.smugmug.com/Photography/Waterfalls-of-North-Georgia/i-sTTL87G/2/58f5fa47/X4/toccoa%20falls%20h-X4.jpg' , description: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.')
 destination2 = Destination.create!(title: 'Chattanooga, TN' , image: 'https://pbs.twimg.com/media/DaNDy2sXkAAxNYG.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing Tennessee River, such as white water rafting, hang-gliding, and hiking.' )
 destination3 = Destination.create!(title:'Athens, GA', image: 'https://i2.wp.com/smoothmoversathens.com/wp-content/uploads/2017/01/athens-ga-real-estate-downtown1.jpg?zoom=2&resize=280%2C280', description: 'home of the University of Georgia as well as a thriving indie music scene. The city has a number of historical buildings with typical Southern architecture in addition to several 18th-century house museums open for touring. A college town, it is quite walkable and packs many venues into its small downtown area.' )
 destination4 = Destination.create!(title: 'Guidestones' , image: 'http://thinkingsidewayspodcast.com/wp-content/uploads/2014/06/GeorgiaGuidestones.jpg', description:'Often referred to as America’s stone henge, the Georgia Guidestones are a set of monolithic structures that were erected in Georgia in March of 1980.' )
 destination5 = Destination.create!(title: 'Brasstown Bald', image: 'http://www.golakechatuge.com/fullpanel/uploads/images/Brasstown%20Bald.jpg', description: 'Georgia’s tallest mountain. Its incredible 360 degree view allows you to see Georgia, North Carolina, Tennessee and South Carolina on a clear day. The changing seasons on Brasstown Bald offer visitors the opportunity to experience the wonders of nature for most of the year. ')
 destination6 = Destination.create!(title: 'Also Dope Spot', image: 'https://www.shutterbug.com/images/17/1jaws1518.jpg', description: 'Banh mi pour-over mixtape small batch, dreamcatcher williamsburg you probably haven\'t heard of them authentic kombucha umami YOLO messenger bag pitchfork slow-carb. Try-hard typewriter fam master cleanse art party, cliche pug palo santo tousled fingerstache gluten-free kinfolk readymade. Ramps trust fund YOLO hammock meh you probably haven\'t heard of them vegan mumblecore church-key. 3 wolf moon')
 destination7 = Destination.create!(title: 'Dope Spot', image: 'https://s-media-cache-ak0.pinimg.com/originals/f7/d9/43/f7d94371aaf7033f700f04bf2b9a629c.jpg', description: 'Pabst craft beer scenester green juice post-ironic aesthetic typewriter snackwave authentic slow-carb church-key succulents shoreditch gochujang YOLO.')
 destination8 = Destination.create!(title: 'Jigokudani Monkey Park', image: 'https://www.ar.jal.co.jp/world/en/guidetojapan/detail/img/jigokudani/jigokudani_01.jpg', description: 'Everyday carry dreamcatcher messenger bag kinfolk, deep v quinoa copper mug wolf vaporware. Bicycle rights tumblr prism, pork belly next level palo santo hell of post-ironic sriracha vape tumeric banh mi. Adaptogen craft beer pinterest heirloom tofu. +1 butcher')
 destination9 = Destination.create!(title: 'Beach!!!', image: 'https://lyndaanneart.files.wordpress.com/2015/07/img_1467.jpg?w=829&h=&crop=1&zoom=2', description: 'Pok pok thundercats messenger bag etsy migas twee coloring book, vegan venmo yuccie green juice quinoa raw denim direct trade. Pour-over swag retro, organic woke slow-carb cliche forage meh humblebrag blog affogato four dollar toast. Godard asymmetrical semiotics pickled leggings.')
 destination10 = Destination.create!(title: 'Woods!!!', image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/IMG_2551.jpg', description: 'Pok pok thundercats messenger bag etsy migas twee coloring book, vegan venmo yuccie green juice quinoa raw denim direct trade. Pour-over swag retro, organic woke slow-carb cliche forage meh humblebrag blog affogato four dollar toast. Godard asymmetrical semiotics pickled leggings.')

image1 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/170501Daily_0.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination1.id  )
image2 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/Narrows%202%20Yellow%20Tree-1%20%20Edit%201.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination1.id )
image3 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/6_6.jpg' , description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination2.id )
image4 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/Sunrise%20pond_1.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination2.id )
image5 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/IMG_3318.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination3.id )
image6 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/DSC_0655-1_0.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination4.id )
image7 = Image.create!(image: 'https://www.shutterbug.com/images/17/2jaws1518.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination5.id)
image8 = Image.create!(image: 'https://www.shutterbug.com/images/17/1jaws1518.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination6.id)
image9 = Image.create!(image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRElvyi9dtTJI_Lmext6SCr_nezQxUpjWjrxiqGsq8CENegPaGm', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination7.id )
image10 = Image.create!(image: 'https://davesboringlife2999.files.wordpress.com/2011/06/20110606-084143.jpg?w=460&zoom=2' , description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination8.id )
image11 = Image.create!(image: 'https://davesboringlife2999.files.wordpress.com/2011/06/20110611-113708.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination9.id)
image12 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/170501Daily_0.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination1.id  )
image13 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/Narrows%202%20Yellow%20Tree-1%20%20Edit%201.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination1.id )
image14 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/6_6.jpg' , description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination2.id )
image15 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/Sunrise%20pond_1.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination2.id )
image16 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/IMG_3318.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination3.id )
image17 = Image.create!(image: 'https://www.shutterbug.com/images/styles/960-wide/public/photo_post/%5Buid%5D/DSC_0655-1_0.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination9.id )
image18 = Image.create!(image: 'https://www.shutterbug.com/images/17/1jaws1518.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination9.id)
image19 = Image.create!(image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRElvyi9dtTJI_Lmext6SCr_nezQxUpjWjrxiqGsq8CENegPaGm', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination10.id )
image20 = Image.create!(image: 'https://davesboringlife2999.files.wordpress.com/2011/06/20110606-084143.jpg?w=460&zoom=2' , description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination10.id )
image21 = Image.create!(image: 'https://davesboringlife2999.files.wordpress.com/2011/06/20110611-113708.jpg', description: 'Has plenty of outdoor fun. In addition to parks and the Riverwalk, there are also a host of adventurous activities to enjoy along the rushing' , destination_id: destination10.id)



post1 = Post.create!(subject: 'Great hike!', image: 'https://vignette.wikia.nocookie.net/dragonballfanon/images/7/70/Random.png/revision/latest?cb=20161221030547', content: 'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid pug selfies hexagon bitters vegan.' ,destination_id: destination1.id)
post2 = Post.create!(subject: 'Purple Durple', image: '', content: 'Bushwick vice mixtape, chillwave enamel pin tattooed ethical brooklyn. Viral cardigan authentic selfies four loko pabst street art health goth intelligentsia. Drinking vinegar pour-over messenger bag trust fund bicycle rights. Williamsburg twee ethical, master cleanse drinking vinegar normcore asymmetrical intelligentsia glossier.',destination_id: destination1.id)
post3 = Post.create!(subject: 'Beautiful!', image: '', content:'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.' ,destination_id: destination1.id)
post4 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination2.id)
post5 = Post.create!(subject: 'Hi mom', image: 'http://images5.fanpop.com/image/photos/31000000/haters-gonna-hate-random-31076705-500-375.jpg', content: 'Bushwick vice mixtape, chillwave enamel pin tattooed ethical brooklyn. Viral cardigan authentic selfies four loko pabst street art health goth intelligentsia. Drinking vinegar pour-over messenger bag trust fund bicycle rights. Williamsburg twee ethical, master cleanse drinking vinegar normcore asymmetrical intelligentsia glossier.',destination_id: destination2.id)
post6 = Post.create!(subject: 'Bring a bathing suit', image:'' , content: 'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid.',destination_id: destination3.id)
post7 = Post.create!(subject: 'Dont forget toilet paper', image:'' , content:'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid.' ,destination_id: destination3.id)
post8 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination3.id)
post9 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination4.id)
post10 = Post.create!(subject: 'Great hike!', image: '', content: 'Bushwick vice mixtape, chillwave enamel pin tattooed ethical brooklyn. Viral cardigan authentic selfies four loko pabst street art health goth intelligentsia. Drinking vinegar pour-over messenger bag trust fund bicycle rights. Williamsburg twee ethical, master cleanse drinking vinegar normcore asymmetrical intelligentsia glossier.',destination_id: destination4.id)
post11 = Post.create!(subject: 'Bring snacks', image: '', content: 'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid pug selfies.' ,destination_id: destination4.id)
post12 = Post.create!(subject: 'Incredible trip.', image: '', content: 'hey howdy',destination_id: destination4.id)
post13 = Post.create!(subject: 'Great hike!', image: '', content:'This is content' ,destination_id: destination5.id)
post14 = Post.create!(subject: 'Great hike!', image: 'https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-1/c1.0.480.480/p480x480/22853197_2001122666774721_1825623692089522085_n.jpg?_nc_cat=0&oh=f2544cab596a4c0e0b073cfa6c48f142&oe=5B7272A6', content: 'Prism glossier tote bag, cloud bread biodiesel hammock bushwick seitan banh mi. Trust fund twee cliche street art venmo thundercats semiotics beard.',destination_id: destination6.id)
post15 = Post.create!(subject: 'Fixies', image: '', content:'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid pug selfies hexagon bitters vegan.' ,destination_id: destination6.id)
post16 = Post.create!(subject: 'Great hike!', image: '', content: 'Helvetica air plant retro tumeric locavore man bun yr pitchfork organic quinoa vinyl master cleanse vape cardigan crucifix. Vape intelligentsia post-ironic, locavore seitan brunch air plant meggings chillwave subway tile pickled next level authentic skateboard godard. Fanny pack artisan taxidermy, literally squid pug selfies hexagon bitters vegan.' ,destination_id: destination7.id)
post17 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination7.id)
post18 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination8.id)
post19 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination9.id)
post20 = Post.create!(subject: 'Beautiful!', image: '', content: 'Sriracha raw denim scenester yuccie squid cold-pressed kale chips chambray swag green juice. Literally farm-to-table wayfarers succulents. Deep v vaporware trust fund lyft chicharrones kombucha street art everyday carry selvage brooklyn glossier normcore cloud bread authentic schlitz.',destination_id: destination10.id)
post21 = Post.create!(subject: 'You\'ve found jet bear!', image: 'https://orig00.deviantart.net/137f/f/2014/147/3/1/random_character__jet_bear_by_mnrart-d7jwteg.gif' , content: 'Bushwick vice mixtape, chillwave enamel pin tattooed ethical brooklyn. Viral cardigan authentic selfies four loko pabst street art health goth intelligentsia. Drinking vinegar pour-over messenger bag trust fund bicycle rights. Williamsburg twee ethical, master cleanse drinking vinegar normcore asymmetrical intelligentsia glossier.',destination_id: destination10.id)
